apiVersion: apps/v1
kind: Deployment
metadata:
 name: greetingsapi
 labels:
    app: greetingsapi
spec:
 replicas: 2
 selector:
    matchLabels:
      app: greetingsapi
 template:
    metadata:
       labels:
        app: greetingsapi
    spec:
      containers:
      - name: greetingsapicontainer
        image: docker.io/jptabja/greetingsapi:v1
        ports:
        - containerPort: 8080